[package]
name = "evault-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true
description = "Terminal user interface for evault."

[lints]
workspace = true

[dependencies]
arboard = "3.6"
evault-core = { path = "../evault-core", version = "0.1.1" }
nucleo-matcher = "0.3"
ratatui = "0.30"
secrecy = "0.10"
thiserror = "2.0"
time = { version = "0.3", features = ["formatting", "macros"] }
