[package]
name = "evault-store-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "In-memory backends for evault (test fixtures)."

[lints]
workspace = true

[dependencies]
evault-core = { path = "../evault-core", version = "0.1.1" }

[dev-dependencies]
time = { version = "0.3", features = ["macros"] }
