//! [`EnvFileMaterializer`] — the production [`Materializer`] impl.

use std::collections::BTreeMap;
use std::fs::{self, File, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

use evault_core::error::MaterializerError;
use evault_core::traits::Materializer;

use crate::gitignore::ensure_gitignore_entry;

/// Header prepended to every materialized file.
///
/// The double-`#` line is treated as a comment by all `.env` parsers and
/// signals to humans that hand-edits will be lost on the next regen.
const HEADER: &str = "\
# Generated by evault — do not edit.
# Run `evault gen --project <path>` to regenerate.
";

/// Filesystem-backed materializer that writes `.env` files atomically
/// with restricted permissions on Unix.
#[derive(Debug, Default, Clone, Copy)]
pub struct EnvFileMaterializer;

impl EnvFileMaterializer {
    /// Construct a fresh `EnvFileMaterializer`. The struct is stateless.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl Materializer for EnvFileMaterializer {
    fn materialize(
        &self,
        path: &Path,
        environment: &BTreeMap<String, String>,
    ) -> Result<(), MaterializerError> {
        // Ensure the parent directory exists. Without this, write of the
        // tempfile fails with NotFound which the user reads as "did
        // evault eat my project?".
        let parent = parent_dir(path);
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(&parent)?;
        }

        // Encode the body. `BTreeMap` iteration is alphabetic by key so
        // the output is deterministic for stable diffs.
        let body = encode(environment);

        // Atomic write through a sibling tempfile.
        let tmp = parent.join(make_tmp_name(path)?);
        write_tempfile_atomically(&tmp, body.as_bytes())?;
        if let Err(e) = fs::rename(&tmp, path) {
            let _ = fs::remove_file(&tmp);
            return Err(MaterializerError::Backend(format!(
                "rename failed: {:?}",
                e.kind()
            )));
        }

        // Best-effort `.gitignore` update; failure here is reported but
        // the .env has already been written successfully.
        ensure_gitignore_entry(&parent, path)
            .map_err(|e| MaterializerError::Backend(format!("gitignore: {e}")))?;

        Ok(())
    }
}

/// Encode an environment as the body of a `.env` file with the
/// `# Generated by evault …` header.
fn encode(environment: &BTreeMap<String, String>) -> String {
    let mut out = String::with_capacity(HEADER.len() + environment.len() * 32);
    out.push_str(HEADER);
    out.push('\n');
    for (k, v) in environment {
        out.push_str(k);
        out.push('=');
        out.push_str(&quote_value(v));
        out.push('\n');
    }
    out
}

/// Quote a value if it contains any character that would alter parsing.
///
/// The conservative rule used here matches every common dotenv parser:
/// quote if the value contains whitespace, `=`, `"`, `'`, or starts with
/// a `#`. We always use double quotes and escape embedded `"` and `\`.
fn quote_value(value: &str) -> String {
    let needs_quote = value.is_empty()
        || value.starts_with('#')
        || value
            .chars()
            .any(|c| c == ' ' || c == '\t' || c == '\n' || c == '=' || c == '"' || c == '\'');
    if !needs_quote {
        return value.to_owned();
    }
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        if c == '"' || c == '\\' {
            out.push('\\');
        }
        out.push(c);
    }
    out.push('"');
    out
}

/// Write `bytes` to a freshly-created tempfile with restrictive perms on
/// Unix, fsync the file, then close it.
fn write_tempfile_atomically(tmp: &Path, bytes: &[u8]) -> Result<(), MaterializerError> {
    let result = (|| -> std::io::Result<()> {
        let mut opts = OpenOptions::new();
        opts.write(true).create_new(true).truncate(false);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            // 0o600: owner read/write only. Required because .env carries
            // resolved secret values.
            opts.mode(0o600);
        }
        let mut f: File = opts.open(tmp)?;
        f.write_all(bytes)?;
        // Flush to disk before the rename. Without this, a power loss
        // between rename and writeback can leave the new file empty on
        // next boot.
        f.sync_all()?;
        Ok(())
    })();
    if let Err(e) = result {
        let _ = fs::remove_file(tmp);
        return Err(MaterializerError::Backend(format!(
            "write tmp: {:?}",
            e.kind()
        )));
    }
    Ok(())
}

fn parent_dir(path: &Path) -> PathBuf {
    path.parent()
        .filter(|p| !p.as_os_str().is_empty())
        .map_or_else(|| PathBuf::from("."), Path::to_path_buf)
}

fn make_tmp_name(path: &Path) -> Result<String, MaterializerError> {
    use std::time::{SystemTime, UNIX_EPOCH};

    let base = path
        .file_name()
        .and_then(|s| s.to_str())
        .ok_or_else(|| MaterializerError::Backend("path has no UTF-8 filename".into()))?;
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |d| d.subsec_nanos());
    let pid = std::process::id();
    Ok(format!(".{base}.tmp.{pid}.{nanos}"))
}
