//! [`EnvFileMaterializer`] — the production [`Materializer`] impl.

use std::collections::BTreeMap;
use std::fs::{self, File, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

use evault_core::error::MaterializerError;
use evault_core::model::Var;
use evault_core::traits::Materializer;

use crate::gitignore::ensure_gitignore_entry;

/// Header prepended to every materialized file.
///
/// The double-`#` line is treated as a comment by all `.env` parsers and
/// signals to humans that hand-edits will be lost on the next regen.
const HEADER: &str = "\
# Generated by evault — do not edit.
# Run `evault gen --project <path>` to regenerate.
";

/// Filesystem-backed materializer that writes `.env` files atomically
/// with restricted permissions on Unix.
#[derive(Debug, Default, Clone, Copy)]
pub struct EnvFileMaterializer;

impl EnvFileMaterializer {
    /// Construct a fresh `EnvFileMaterializer`. The struct is stateless.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }
}

impl Materializer for EnvFileMaterializer {
    fn materialize(
        &self,
        path: &Path,
        environment: &BTreeMap<String, String>,
    ) -> Result<(), MaterializerError> {
        // Validate every key and value BEFORE touching disk. Any single
        // invalid entry rejects the whole materialization — partial files
        // are never written.
        validate_environment(environment)?;

        // Ensure the parent directory exists. Map the OS error to a
        // category label so the OS error message and any echoed path
        // don't leak through the public error.
        let parent = parent_dir(path);
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(&parent).map_err(|e| {
                MaterializerError::Backend(format!("create parent dir: {:?}", e.kind()))
            })?;
        }

        // Encode the body. `BTreeMap` iteration is alphabetic by key so
        // the output is deterministic for stable diffs.
        let body = encode(environment);

        // Atomic write through a sibling tempfile.
        let tmp = parent.join(make_tmp_name(path)?);
        write_tempfile_atomically(&tmp, body.as_bytes())?;
        if let Err(e) = fs::rename(&tmp, path) {
            let _ = fs::remove_file(&tmp);
            return Err(MaterializerError::Backend(format!(
                "rename failed: {:?}",
                e.kind()
            )));
        }

        // Update `.gitignore`. A failure here is dangerous: the .env has
        // already landed and may be picked up by `git add .`, leaking
        // secrets. We roll back the .env (best-effort delete) and surface
        // the failure to the caller so they can fix the underlying issue
        // and retry.
        if let Err(e) = ensure_gitignore_entry(&parent, path) {
            let _ = fs::remove_file(path);
            return Err(MaterializerError::Backend(format!(
                "gitignore: {:?}; .env rolled back to avoid leaving an \
                 unignored secret file on disk",
                e.kind()
            )));
        }

        Ok(())
    }
}

/// Reject any key or value whose shape could break the `.env` format or
/// open an injection vector.
///
/// - Keys must satisfy [`Var::validate_name`] — the same rules the
///   registry enforces. Keys ARE included in the error message (they are
///   not secret material per `evault`'s design).
/// - Values must NOT contain any control character. Newlines in
///   particular allow `KEY=...\nOTHER=evil` injection because dotenv
///   parsers handle multi-line quoted values inconsistently. Multi-line
///   secrets (PEM keys, JSON blobs) should be base64-encoded or stored
///   under separate keys.
fn validate_environment(env: &BTreeMap<String, String>) -> Result<(), MaterializerError> {
    for (key, value) in env {
        Var::validate_name(key)
            .map_err(|_| MaterializerError::Backend(format!("invalid key name: {key:?}")))?;
        if let Some(bad) = value.chars().find(|c| c.is_control() && *c != '\t') {
            // Echo the key (not secret) and the byte category. Never the
            // surrounding value text.
            let kind = match bad {
                '\n' => "newline",
                '\r' => "carriage return",
                '\0' => "NUL byte",
                _ => "control byte",
            };
            return Err(MaterializerError::Backend(format!(
                "value for key {key:?} contains a {kind}; \
                 .env cannot represent it portably — base64-encode the \
                 value or split it across separate keys"
            )));
        }
    }
    Ok(())
}

/// Encode an environment as the body of a `.env` file with the
/// `# Generated by evault …` header.
fn encode(environment: &BTreeMap<String, String>) -> String {
    let mut out = String::with_capacity(HEADER.len() + environment.len() * 32);
    out.push_str(HEADER);
    out.push('\n');
    for (k, v) in environment {
        out.push_str(k);
        out.push('=');
        out.push_str(&quote_value(v));
        out.push('\n');
    }
    out
}

/// Quote a value if it contains any character that would alter parsing.
///
/// The input has already been validated by [`validate_environment`] so
/// no control characters (other than `\t`) can appear here. The function
/// double-quotes when the value is empty, starts with `#`, or contains
/// whitespace, `=`, `"`, or `'`; embedded `"` and `\` are backslash-
/// escaped inside the quoted form. Bare values pass through unchanged.
fn quote_value(value: &str) -> String {
    let needs_quote = value.is_empty()
        || value.starts_with('#')
        || value
            .chars()
            .any(|c| c == ' ' || c == '\t' || c == '=' || c == '"' || c == '\'');
    if !needs_quote {
        return value.to_owned();
    }
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        if c == '"' || c == '\\' {
            out.push('\\');
        }
        out.push(c);
    }
    out.push('"');
    out
}

/// Write `bytes` to a freshly-created tempfile with restrictive perms on
/// Unix, fsync the file, then close it.
fn write_tempfile_atomically(tmp: &Path, bytes: &[u8]) -> Result<(), MaterializerError> {
    let result = (|| -> std::io::Result<()> {
        let mut opts = OpenOptions::new();
        // `create_new` is O_CREAT|O_EXCL so the file is always brand new.
        // `truncate` is redundant under this mode.
        opts.write(true).create_new(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            // 0o600: owner read/write only. Required because .env carries
            // resolved secret values.
            opts.mode(0o600);
        }
        let mut f: File = opts.open(tmp)?;
        f.write_all(bytes)?;
        // Flush to disk before the rename. Without this, a power loss
        // between rename and writeback can leave the new file empty on
        // next boot.
        f.sync_all()?;
        Ok(())
    })();
    if let Err(e) = result {
        let _ = fs::remove_file(tmp);
        return Err(MaterializerError::Backend(format!(
            "write tmp: {:?}",
            e.kind()
        )));
    }
    Ok(())
}

fn parent_dir(path: &Path) -> PathBuf {
    path.parent()
        .filter(|p| !p.as_os_str().is_empty())
        .map_or_else(|| PathBuf::from("."), Path::to_path_buf)
}

fn make_tmp_name(path: &Path) -> Result<String, MaterializerError> {
    use std::time::{SystemTime, UNIX_EPOCH};

    let base = path
        .file_name()
        .and_then(|s| s.to_str())
        .ok_or_else(|| MaterializerError::Backend("path has no UTF-8 filename".into()))?;
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |d| d.subsec_nanos());
    let pid = std::process::id();
    Ok(format!(".{base}.tmp.{pid}.{nanos}"))
}
