//! `.env` file generator that satisfies the
//! [`Materializer`](evault_core::traits::Materializer) trait.
//!
//! [`EnvFileMaterializer`] writes a `KEY=VALUE` file with a
//! `# Generated by evault — do not edit` header, ensures the parent
//! directory exists, and updates a sibling `.gitignore` so the basename
//! of the output is git-ignored.
//!
//! # Atomicity
//!
//! Writes go through a sibling tempfile then `fs::rename` so a crash or
//! out-of-space mid-write never leaves a partial `.env` visible at the
//! target path. The tempfile lives in the same directory, which keeps
//! the rename on a single volume (a requirement for atomicity on
//! Windows).
//!
//! On Unix the tempfile is created with mode `0o600` so the resolved
//! secret values are readable only by the owning user. On Windows the
//! file inherits the directory's ACL — the user is expected to be the
//! owner.
//!
//! # Durability
//!
//! After writing the body and before `rename`, the tempfile is flushed
//! to disk via [`std::fs::File::sync_all`]. Without this, a power loss
//! between rename and writeback could leave the new file at the target
//! path with empty or truncated contents on next boot.
//!
//! # Examples
//!
//! ```
//! use std::collections::BTreeMap;
//! use evault_core::traits::Materializer;
//! use evault_materializer::EnvFileMaterializer;
//!
//! let dir = tempfile::tempdir().unwrap();
//! let path = dir.path().join(".env");
//! let mut env = BTreeMap::new();
//! env.insert("NODE_ENV".to_string(), "production".to_string());
//!
//! EnvFileMaterializer::new()
//!     .materialize(&path, &env)
//!     .unwrap();
//!
//! let body = std::fs::read_to_string(&path).unwrap();
//! assert!(body.contains("NODE_ENV=production"));
//! ```
#![forbid(unsafe_code)]

mod env_file;
mod gitignore;
mod target;

pub use env_file::EnvFileMaterializer;
pub use target::{env_file_path, validate_environment_label};
