//! Integration tests for `EnvFileMaterializer`.

#![allow(clippy::expect_used)]

use std::collections::BTreeMap;

use evault_core::traits::Materializer;
use evault_materializer::EnvFileMaterializer;
use tempfile::TempDir;

fn env(entries: &[(&str, &str)]) -> BTreeMap<String, String> {
    entries
        .iter()
        .map(|(k, v)| ((*k).to_owned(), (*v).to_owned()))
        .collect()
}

#[test]
fn materialize_writes_alphabetized_keys_with_header() {
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    EnvFileMaterializer::new()
        .materialize(&path, &env(&[("ZED", "z"), ("ALPHA", "a"), ("BETA", "b")]))
        .expect("materialize");

    let body = std::fs::read_to_string(&path).expect("read");
    assert!(body.contains("# Generated by evault"));
    let kv_lines: Vec<&str> = body
        .lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .collect();
    assert_eq!(kv_lines, vec!["ALPHA=a", "BETA=b", "ZED=z"]);
}

#[test]
fn materialize_quotes_values_with_special_chars() {
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    EnvFileMaterializer::new()
        .materialize(
            &path,
            &env(&[
                ("WITH_SPACE", "hello world"),
                ("WITH_EQUALS", "a=b"),
                ("WITH_QUOTE", "say \"hi\""),
                ("STARTS_WITH_HASH", "#not-a-comment"),
                ("EMPTY", ""),
            ]),
        )
        .expect("materialize");

    let body = std::fs::read_to_string(&path).expect("read");
    assert!(body.contains(r#"WITH_SPACE="hello world""#));
    assert!(body.contains(r#"WITH_EQUALS="a=b""#));
    assert!(body.contains(r#"WITH_QUOTE="say \"hi\"""#));
    assert!(body.contains("STARTS_WITH_HASH=\"#not-a-comment\""));
    assert!(body.contains(r#"EMPTY="""#));
}

#[test]
fn materialize_rejects_value_with_newline() {
    // Multi-line secrets (CRLF injection vector) MUST be rejected up-front.
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    let err = EnvFileMaterializer::new()
        .materialize(&path, &env(&[("TOKEN", "abc\nADMIN=true")]))
        .expect_err("should reject newline");
    let msg = format!("{err:?}");
    assert!(msg.contains("newline"), "expected newline mention: {msg}");
    assert!(msg.contains("TOKEN"), "expected key mention: {msg}");
    // CRITICAL: no part of the value text after the newline should appear
    // in the error string (would leak secret material).
    assert!(!msg.contains("ADMIN=true"), "value text leaked: {msg}");
    // No file should have been written.
    assert!(!path.exists(), ".env should not exist after rejection");
}

#[test]
fn materialize_rejects_value_with_carriage_return() {
    // CR alone (Windows-style line endings without LF) is also a vector.
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    let err = EnvFileMaterializer::new()
        .materialize(&path, &env(&[("TOKEN", "abc\rADMIN=true")]))
        .expect_err("should reject CR");
    let msg = format!("{err:?}");
    assert!(
        msg.contains("carriage return"),
        "expected CR mention: {msg}"
    );
    assert!(!path.exists());
}

#[test]
fn materialize_rejects_value_with_nul_byte() {
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    let err = EnvFileMaterializer::new()
        .materialize(&path, &env(&[("TOKEN", "abc\0xyz")]))
        .expect_err("should reject NUL");
    let msg = format!("{err:?}");
    assert!(msg.contains("NUL"), "expected NUL mention: {msg}");
    assert!(!path.exists());
}

#[test]
fn materialize_accepts_tab_in_value() {
    // Tab is the only control char we allow — common in legitimate
    // structured values like base64 with embedded whitespace.
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    EnvFileMaterializer::new()
        .materialize(&path, &env(&[("FOO", "a\tb")]))
        .expect("tab should be quoted, not rejected");
    let body = std::fs::read_to_string(&path).expect("read");
    assert!(body.contains("FOO=\"a\tb\""));
}

#[test]
fn materialize_rejects_invalid_key_name() {
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    // Spaces in keys break the .env format entirely.
    let err = EnvFileMaterializer::new()
        .materialize(&path, &env(&[("WITH SPACE", "v")]))
        .expect_err("should reject space in key");
    let msg = format!("{err:?}");
    assert!(msg.contains("invalid key"), "expected invalid key: {msg}");
    // Keys starting with a digit are also rejected by Var::validate_name.
    let err = EnvFileMaterializer::new()
        .materialize(&path, &env(&[("1BAD", "v")]))
        .expect_err("should reject leading digit");
    let msg = format!("{err:?}");
    assert!(msg.contains("invalid key"), "expected invalid key: {msg}");
}

#[test]
fn materialize_does_not_quote_plain_values() {
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    EnvFileMaterializer::new()
        .materialize(&path, &env(&[("NODE_ENV", "production")]))
        .expect("materialize");
    let body = std::fs::read_to_string(&path).expect("read");
    // Bare assignment, no quoting around `production`.
    assert!(body.contains("NODE_ENV=production"));
    assert!(!body.contains("NODE_ENV=\"production\""));
}

#[test]
fn materialize_creates_parent_directory_if_missing() {
    let dir = TempDir::new().expect("tmpdir");
    let nested = dir.path().join("a").join("b").join(".env");
    EnvFileMaterializer::new()
        .materialize(&nested, &env(&[("FOO", "bar")]))
        .expect("materialize");
    assert!(nested.exists(), "nested .env should be written");
}

#[test]
fn materialize_adds_gitignore_entry_when_absent() {
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    EnvFileMaterializer::new()
        .materialize(&path, &env(&[("FOO", "bar")]))
        .expect("materialize");

    let gitignore = std::fs::read_to_string(dir.path().join(".gitignore")).expect("read");
    assert!(
        gitignore.contains("/.env"),
        "expected /.env in:\n{gitignore}"
    );
}

#[test]
fn materialize_does_not_duplicate_gitignore_entry() {
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    EnvFileMaterializer::new()
        .materialize(&path, &env(&[("FOO", "bar")]))
        .expect("first");
    EnvFileMaterializer::new()
        .materialize(&path, &env(&[("FOO", "bar")]))
        .expect("second");

    let gitignore = std::fs::read_to_string(dir.path().join(".gitignore")).expect("read");
    let count = gitignore.lines().filter(|l| l.trim() == "/.env").count();
    assert_eq!(
        count, 1,
        "expected exactly one /.env entry, got:\n{gitignore}"
    );
}

#[test]
fn materialize_preserves_existing_gitignore_entries() {
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    std::fs::write(dir.path().join(".gitignore"), "target/\nnode_modules/\n").expect("seed");

    EnvFileMaterializer::new()
        .materialize(&path, &env(&[("FOO", "bar")]))
        .expect("materialize");

    let gitignore = std::fs::read_to_string(dir.path().join(".gitignore")).expect("read");
    assert!(gitignore.contains("target/"), "original entries preserved");
    assert!(gitignore.contains("node_modules/"));
    assert!(gitignore.contains("/.env"));
}

#[test]
fn materialize_recognizes_basename_form_in_existing_gitignore() {
    // If the user already has `.env` (without leading slash), don't
    // append a redundant `/.env` entry.
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    std::fs::write(dir.path().join(".gitignore"), ".env\n").expect("seed");

    EnvFileMaterializer::new()
        .materialize(&path, &env(&[("FOO", "bar")]))
        .expect("materialize");

    let gitignore = std::fs::read_to_string(dir.path().join(".gitignore")).expect("read");
    assert!(
        !gitignore.contains("/.env"),
        "should not add /.env on top of .env"
    );
}

#[test]
fn materialize_overwrites_existing_env_file() {
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    std::fs::write(&path, "OLD=stale\n").expect("seed");

    EnvFileMaterializer::new()
        .materialize(&path, &env(&[("NEW", "fresh")]))
        .expect("materialize");

    let body = std::fs::read_to_string(&path).expect("read");
    assert!(body.contains("NEW=fresh"));
    assert!(!body.contains("OLD=stale"));
}

#[test]
fn materialize_leaves_no_tempfile_behind_on_success() {
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    EnvFileMaterializer::new()
        .materialize(&path, &env(&[("FOO", "bar")]))
        .expect("materialize");

    let entries: Vec<_> = std::fs::read_dir(dir.path())
        .expect("read_dir")
        .filter_map(Result::ok)
        .map(|e| e.file_name())
        .collect();
    assert_eq!(
        entries.len(),
        2,
        "expected .env + .gitignore only, got: {entries:?}"
    );
}

#[cfg(unix)]
#[test]
fn materialize_sets_0o600_permissions_on_unix() {
    use std::os::unix::fs::PermissionsExt;
    let dir = TempDir::new().expect("tmpdir");
    let path = dir.path().join(".env");
    EnvFileMaterializer::new()
        .materialize(&path, &env(&[("API_KEY", "sk-secret")]))
        .expect("materialize");

    let meta = std::fs::metadata(&path).expect("metadata");
    let mode = meta.permissions().mode() & 0o777;
    assert_eq!(
        mode, 0o600,
        ".env should be owner-only readable; got {mode:o}"
    );
}
